fix: an error is thrown when when a devices src id changes (#284)
n2k-signalk: address 0 changed from c0328700227b5a77 c0509b002270da77
TypeError: Cannot set properties of undefined (setting '60928')
    at N2kMapper.toDelta
        (/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/n2k-signalk/n2kMapper.js:140:51)